
  create table "public"."student" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid default auth.uid(),
    "subjects" uuid[] not null,
    "enrolment_id" uuid,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."student" enable row level security;

CREATE UNIQUE INDEX student_pkey ON public.student USING btree (id);

alter table "public"."student" add constraint "student_pkey" PRIMARY KEY using index "student_pkey";

alter table "public"."student" add constraint "student_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."user"(id) not valid;

alter table "public"."student" validate constraint "student_user_id_fkey";

grant delete on table "public"."student" to "anon";

grant insert on table "public"."student" to "anon";

grant references on table "public"."student" to "anon";

grant select on table "public"."student" to "anon";

grant trigger on table "public"."student" to "anon";

grant truncate on table "public"."student" to "anon";

grant update on table "public"."student" to "anon";

grant delete on table "public"."student" to "authenticated";

grant insert on table "public"."student" to "authenticated";

grant references on table "public"."student" to "authenticated";

grant select on table "public"."student" to "authenticated";

grant trigger on table "public"."student" to "authenticated";

grant truncate on table "public"."student" to "authenticated";

grant update on table "public"."student" to "authenticated";

grant delete on table "public"."student" to "service_role";

grant insert on table "public"."student" to "service_role";

grant references on table "public"."student" to "service_role";

grant select on table "public"."student" to "service_role";

grant trigger on table "public"."student" to "service_role";

grant truncate on table "public"."student" to "service_role";

grant update on table "public"."student" to "service_role";


