
  create table "public"."marks" (
    "id" bigint generated by default as identity not null,
    "value" real,
    "created_at" timestamp with time zone not null default now(),
    "student_id" uuid not null default auth.uid()
      );


alter table "public"."marks" enable row level security;

alter table "public"."student" alter column "id" set default gen_random_uuid();

alter table "public"."student" alter column "id" drop identity;

alter table "public"."student" alter column "id" set data type uuid using "id"::uuid;

CREATE UNIQUE INDEX marks_pkey ON public.marks USING btree (id, student_id);

alter table "public"."marks" add constraint "marks_pkey" PRIMARY KEY using index "marks_pkey";

grant delete on table "public"."marks" to "anon";

grant insert on table "public"."marks" to "anon";

grant references on table "public"."marks" to "anon";

grant select on table "public"."marks" to "anon";

grant trigger on table "public"."marks" to "anon";

grant truncate on table "public"."marks" to "anon";

grant update on table "public"."marks" to "anon";

grant delete on table "public"."marks" to "authenticated";

grant insert on table "public"."marks" to "authenticated";

grant references on table "public"."marks" to "authenticated";

grant select on table "public"."marks" to "authenticated";

grant trigger on table "public"."marks" to "authenticated";

grant truncate on table "public"."marks" to "authenticated";

grant update on table "public"."marks" to "authenticated";

grant delete on table "public"."marks" to "postgres";

grant insert on table "public"."marks" to "postgres";

grant references on table "public"."marks" to "postgres";

grant select on table "public"."marks" to "postgres";

grant trigger on table "public"."marks" to "postgres";

grant truncate on table "public"."marks" to "postgres";

grant update on table "public"."marks" to "postgres";

grant delete on table "public"."marks" to "service_role";

grant insert on table "public"."marks" to "service_role";

grant references on table "public"."marks" to "service_role";

grant select on table "public"."marks" to "service_role";

grant trigger on table "public"."marks" to "service_role";

grant truncate on table "public"."marks" to "service_role";

grant update on table "public"."marks" to "service_role";


